sudo: required
services:
  - docker

before_install:
  - docker build -t shonry27/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shonry27/react-test npm test -- --coverage

after_success:
  - docker build -t shonry27/multi-client ./client
  - docker build -t shonry27/multi-nginx ./nginx
  - docker build -t shonry27/multi-server ./server
  - docker build -t shonry27/multi-worker ./worker
  # Login to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to Docker Hub
  - docker push shonry27/multi-client
  - docker push shonry27/multi-nginx
  - docker push shonry27/multi-server
  - docker push shonry27/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-032386328462
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
